server:
  port: 9898
spring:
  datasource:
    url: jdbc:h2:mem:mydb
  h2:
    console:
      enabled: true
  application:
    name: AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


jwt:
  secret: 7136a88d4b4b8b378ed192f41a1a0aa884dc671753492790c58ab939bc010465
