server:
  port: 9192
spring:
  datasource:
    url: jdbc:h2:mem:mydb
  h2:
    console:
      enabled: true
  application:
    name: ORDER-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
