spring:
#  main:
#    web-application-type: reactive
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/order/**
        filters:
          - JwtAuthFilter

      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
          - Path=/payment/**
        filters:
          - JwtAuthFilter

      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8989

jwt:
  secret: 7136a88d4b4b8b378ed192f41a1a0aa884dc671753492790c58ab939bc010465

